BackEnd:
  VersionDONOTCHANGE: 2
  UpdateChecking: true
  Metrics: true
Players:
  AllowedOp:
    - EnkyHD
  AllowedGamemode:
    - EnkyHD
Block:
  PlayersFromChangingGameMode: true
  OPingNonAllowedOPs: true
  OPInConsole: true
Stats:
  blockedInConsole: 0
  blockedByCommand: 0
  playersDeopOnJoin: 0
